apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "base.mgmtBackend" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    app.kubernetes.io/component: mgmt-backend
data:
  config.yaml: |+
    server:
      privateport: {{ template "base.mgmtBackend.privatePort" . }}
      publicport: {{ template "base.mgmtBackend.publicPort" . }}
      edition: {{ .Values.edition }}
      usage:
        {{- toYaml .Values.usage | nindent 8 }}
      debug: {{ ternary "true" "false" (eq (.Values.logLevel | upper) "DEBUG") }}
      {{- if .Values.internalTLS.enabled }}
      https:
        cert: /etc/instill-ai/base/ssl/mgmt/tls.crt
        key: /etc/instill-ai/base/ssl/mgmt/tls.key
      {{- end }}
    database:
      username: {{ default (include "base.database.username" .) .Values.database.external.username }}
      password: {{ default (include "base.database.rawPassword" .) .Values.database.external.password }}
      host: {{ default (include "base.database.host" .) .Values.database.external.host }}
      port: {{ default (include "base.database.port" .) .Values.database.external.port }}
      name: mgmt
      version: {{ .Values.mgmtBackend.dbVersion }}
      timezone: Etc/UTC
      pool:
        idleconnections: {{ .Values.database.maxIdleConns }}
        maxconnections: {{ .Values.database.maxOpenConns }}
        connlifetime: {{ .Values.database.maxConnLifeTime }}
    cache:
      redis:
        redisoptions:
          addr: {{ default (include "base.redis.addr" .) .Values.redis.external.addr }}
    influxdb:
      url: {{ template "base.influxdb.url" . }}
      token: {{ .Values.influxdb2.adminUser.token }}
      org: {{ .Values.influxdb2.adminUser.organization }}
      bucket: {{ (index .Values.influxdb2.env 0).value }}
      flushinterval: 10 # In seconds for non-blocking batch mode
      https:
        cert:
        key:
    log:
      external: {{ .Values.tags.observability }}
      otelcollector:
        host: {{ template "base.otel" . }}
        port: {{ template "base.otel.port" . }}
