apiVersion: v1
kind: Service
metadata:
  name: {{ template "base.mgmtBackend" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
    app.kubernetes.io/component: mgmt-backend
  {{- with .Values.mgmtBackend.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: {{ ternary "https" "http" .Values.internalTLS.enabled }}-private
      port: {{ template "base.mgmtBackend.privatePort" . }}
      targetPort: {{ template "base.mgmtBackend.privatePort" . }}
    - name: {{ ternary "https" "http" .Values.internalTLS.enabled }}-public
      port: {{ template "base.mgmtBackend.publicPort" . }}
      targetPort: {{ template "base.mgmtBackend.publicPort" . }}
  selector:
    {{- include "base.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: mgmt-backend
