version: "3.9"

services:
  api_gateway:
    profiles:
      - all
      - mgmt
      - console
      - pipeline
      - connector
      - controller-vdp
      - model
      - controller-model
    image: ${API_GATEWAY_IMAGE}:latest
    environment:
      API_GATEWAY_LOG_LEVEL: DEBUG

  mgmt_backend_migrate:
    profiles:
      - all
      - api-gateway
      - console
      - pipeline
      - connector
      - controller-vdp
      - model
      - controller-model
    image: ${MGMT_BACKEND_IMAGE}:latest

  mgmt_backend_init:
    profiles:
      - all
      - api-gateway
      - console
      - pipeline
      - connector
      - controller-vdp
      - model
      - controller-model
    image: ${MGMT_BACKEND_IMAGE}:latest

  mgmt_backend:
    profiles:
      - all
      - api-gateway
      - console
      - pipeline
      - connector
      - controller-vdp
      - model
      - controller-model
    image: ${MGMT_BACKEND_IMAGE}:latest
    environment:
      CFG_SERVER_DEBUG: "true"
      CFG_SERVER_EDITION: ${EDITION}
    ports:
      - ${MGMT_BACKEND_PRIVATEPORT}:${MGMT_BACKEND_PRIVATEPORT}
      - ${MGMT_BACKEND_PUBLICPORT}:${MGMT_BACKEND_PUBLICPORT}

  console:
    profiles:
      - all
      - api-gateway
      - mgmt
      - pipeline
      - connector
      - controller-vdp
      - model
      - controller-model
    image: ${CONSOLE_IMAGE}:latest
    environment:
      NEXT_PUBLIC_USAGE_COLLECTION_ENABLED: ${USAGE_ENABLED}
      NEXT_PUBLIC_CONSOLE_EDITION: ${EDITION}
      NODE_ENV: development
    ports:
      - ${CONSOLE_PORT}:${CONSOLE_PORT}

  pg_sql:
    ports:
      - ${POSTGRESQL_PORT}:5432

  temporal:
    ports:
      - ${TEMPORAL_PORT}:7233

  redis:
    ports:
      - ${REDIS_PORT}:6379

  etcd:
    ports:
      - ${ETCD_CLIENT_PORT}:${ETCD_CLIENT_PORT}
