version: "3.9"

services:
  otel_collector:
    container_name: ${OTEL_COLLECTOR_HOST}
    image: ${OTEL_COLLECTOR_IMAGE}:${OTEL_COLLECTOR_VERSION}
    command: --config=/configs/otel-collector/config.yaml
    volumes:
      - ${OBSERVE_CONFIG_DIR_PATH}:/configs
    depends_on:
      - jaeger
      - prometheus

  jaeger:
    container_name: ${JAEGER_HOST}
    image: ${JAEGER_IMAGE}:${JAEGER_VERSION}
    ports:
      - ${JAEGER_WEB_PORT}:16686 # Web HTTP

  prometheus:
    container_name: ${PROMETHEUS_HOST}
    image: ${PROMETHEUS_IMAGE}:v${PROMETHEUS_VERSION}
    command:
      - --config.file=/configs/prometheus/config.yaml
    volumes:
      - ${OBSERVE_CONFIG_DIR_PATH}:/configs
    ports:
      - ${PROMETHEUS_WEB_PORT}:9090

  grafana:
    container_name: ${GRAFANA_HOST}
    image: ${GRAFANA_IMAGE}:${GRAFANA_VERSION}
    volumes:
      - ${OBSERVE_CONFIG_DIR_PATH}/grafana/datasources/all.yml:/etc/grafana/provisioning/datasources/all.yml
      - ${OBSERVE_CONFIG_DIR_PATH}/grafana/dashboards/all.yml:/etc/grafana/provisioning/dashboards/all.yml
      - ${OBSERVE_CONFIG_DIR_PATH}/grafana/krakend:/var/lib/grafana/dashboards/krakend
      - ${OBSERVE_CONFIG_DIR_PATH}/grafana/ray:/var/lib/grafana/dashboards/ray
    ports:
      - ${GRAFANA_PORT}:3000
