version: "3.9"

services:
  api_gateway:
    image: ${API_GATEWAY_IMAGE}:${API_GATEWAY_VERSION}
    build:
      context: ./${API_GATEWAY_HOST}
      args:
        SERVICE_NAME: api-gateway
        GOLANG_VERSION: 1.21.3
        ALPINE_VERSION: 3.18
        KRAKEND_CE_VERSION: ${KRAKEND_CE_VERSION}
    profiles:
      - all
      - exclude-console
      - exclude-pipeline
      - exclude-controller-vdp
      - exclude-model
      - exclude-controller-model
      - exclude-mgmt

  mgmt_backend:
    image: ${MGMT_BACKEND_IMAGE}:${MGMT_BACKEND_VERSION}
    build:
      context: ./${MGMT_BACKEND_HOST}
      args:
        SERVICE_NAME: ${MGMT_BACKEND_HOST}
        GOLANG_VERSION: ${GOLANG_VERSION}
        K6_VERSION: ${K6_VERSION}
    profiles:
      - all
      - exclude-api-gateway
      - exclude-console
      - exclude-pipeline
      - exclude-controller-vdp
      - exclude-model
      - exclude-controller-model

  console:
    image: ${CONSOLE_IMAGE}:${CONSOLE_VERSION}
    build:
      context: ./${CONSOLE_HOST}
    profiles:
      - all
      - exclude-api-gateway
      - exclude-pipeline
      - exclude-controller-vdp
      - exclude-model
      - exclude-controller-model
      - exclude-mgmt

  console_playwright:
    image: ${CONSOLE_IMAGE}-playwright:${CONSOLE_VERSION}
    build:
      context: ./${CONSOLE_HOST}
      dockerfile: Dockerfile.playwright
      args:
        TEST_USER: "root"
    profiles:
      - all
      - exclude-api-gateway
      - exclude-console
      - exclude-pipeline
      - exclude-controller-vdp
      - exclude-model
      - exclude-controller-model
      - exclude-mgmt
