version: "3.9"

services:
  api_gateway_base:
    image: ${API_GATEWAY_BASE_IMAGE}:${API_GATEWAY_BASE_VERSION}
    build:
      context: ./api-gateway
      args:
        SERVICE_NAME: ${API_GATEWAY_BASE_HOST}
        GOLANG_VERSION: ${GOLANG_VERSION}
        ALPINE_VERSION: ${ALPINE_VERSION}
        KRAKEND_CE_VERSION: ${KRAKEND_CE_VERSION}

  mgmt_backend:
    image: ${MGMT_BACKEND_IMAGE}:${MGMT_BACKEND_VERSION}
    build:
      context: ./${MGMT_BACKEND_HOST}
      args:
        SERVICE_NAME: ${MGMT_BACKEND_HOST}
        GOLANG_VERSION: ${GOLANG_VERSION}
        K6_VERSION: ${K6_VERSION}

  console:
    image: ${CONSOLE_IMAGE}:${CONSOLE_VERSION}
    build:
      context: ./${CONSOLE_HOST}

  console_playwright:
    image: ${CONSOLE_IMAGE}-playwright:${CONSOLE_VERSION}
    build:
      context: ./${CONSOLE_HOST}
      dockerfile: Dockerfile.playwright
      args:
        TEST_USER: "root"
