name: Make All

on:
  workflow_dispatch:
  push:
    branches:
      - release-please--branches--main
    tags:
      - v*

jobs:
  make-all:
    runs-on: ubuntu-latest
    steps:
      # mono occupies port 8084 which conflicts with mgmt-backend
      - name: Stop mono service
        run: |
          sudo kill -9 `sudo lsof -t -i:8084`
          sudo lsof -i -P -n | grep LISTEN

      - name: Free disk space
        run: |
          df --human-readable
          sudo apt clean
          docker rmi $(docker image ls --all --quiet)
          rm --recursive --force "$AGENT_TOOLSDIRECTORY"
          df --human-readable

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: instill-ai/base

      - name: Load .env file
        uses: cardinalby/export-env-action@v2
        with:
          envFile: .env

      - name: Install k6
        run: |
          curl https://github.com/grafana/k6/releases/download/v${{ env.K6_VERSION }}/k6-v${{ env.K6_VERSION }}-linux-amd64.tar.gz -L | tar xvz --strip-components 1 && sudo cp k6 /usr/bin

      - name: Launch Instill Base (release)
        run: |
          make all EDITION=local-ce:test

      - name: List all docker containers
        run: |
          docker ps -a
          sleep 60

      - name: Probe to base (influxdb, temporal and console) healthcheck endpoint
        run: |
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8086/health
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8088/health
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:3000

      - name: Probe to base services healthcheck endpoint
        run: |
          curl -s -o /dev/null -w ''%{http_code}'\n' http://localhost:8080/base/v1alpha/health/mgmt

      - name: Tear down Instill Base (release)
        run: |
          make down
